# Generated by Django 4.1.3 on 2022-12-24 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('discounted_price', models.FloatField()),
                ('desc', models.TextField()),
                ('composition', models.TextField(default='')),
                ('prodapp', models.TextField(default='')),
                ('category', models.CharField(choices=[('CR', 'Curd'), ('ML', 'Milk'), ('PN', 'Paneer'), ('Ic', 'Icecream'), ('GH', 'Ghee'), ('CZ', 'Cheese')], max_length=2)),
                ('image', models.ImageField(upload_to='product')),
            ],
        ),
    ]
